spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Android1.
    url: jdbc:mysql://120.46.136.163:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev4
girl:
  name: lili_
  age: 18
